#!/usr/bin/env bash
set -euo pipefail
trap 'echo "Error on line $LINENO: command exited with status $?"' ERR

# -----------------------------------------------------------------------------
# Check if the device is a Raspberry Pi
if ! grep -q "Raspberry Pi" /proc/device-tree/model 2>/dev/null; then
    echo "This installation script is only for the Raspberry Pi!"
    exit 1
fi

# -----------------------------------------------------------------------------
# Must be run as root
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run with sudo or as root"
    exit 1
fi

USER_NAME="${SUDO_USER:-$USER}"
USER_HOME=$(eval echo "~$USER_NAME")
USER_BASHRC="$USER_HOME/.bashrc"
ROOT_DIR="$(pwd -P)"

# -----------------------------------------------------------------------------
# Prompt for EYE_ID
printf "Enter EYE_ID (1 through 6): "
read -r EYE_ID

case "$EYE_ID" in
    ''|*[!0-9]*)
        echo "EYE_ID must be an integer"
        exit 1
        ;;
esac

if ! [[ "$EYE_ID" =~ ^[1-6]$ ]]; then
    echo "EYE_ID must be an integer between 1 and 6"
    exit 1
fi

# -----------------------------------------------------------------------------
# Set the hostname
NEW_HOSTNAME="eye${EYE_ID}"
echo "Updating hostname to: $NEW_HOSTNAME"
hostnamectl set-hostname "$NEW_HOSTNAME"
sed -i "s/^127.0.1.1.*/127.0.1.1    $NEW_HOSTNAME/" /etc/hosts

# -----------------------------------------------------------------------------
# Regenerate machine-id (required after SD card clone to prevent DHCP/ARP conflicts)
echo "Regenerating machine-id..."
rm -f /etc/machine-id
dbus-uuidgen --ensure=/etc/machine-id
rm -f /var/lib/dbus/machine-id
ln -sf /etc/machine-id /var/lib/dbus/machine-id

# -----------------------------------------------------------------------------
# Update firmware config:
# Reduce clocks, setup LCD, and setup CAN
CFG="/boot/firmware/config.txt"

echo "Updating firmware: $CFG"

tee "$CFG" >/dev/null <<'EOF'
# Generated by ./aEyes/eye/install.sh
# Raspberry Pi firmware configuration

# Parameters from default installation
dtparam=audio=off
camera_auto_detect=0
auto_initramfs=1
arm_64bit=1
disable_overscan=1

[cm4]
otg_mode=1

[all]
# Reduce clocks for lower power consumption
arm_freq=600
gpu_freq=500
over_voltage=0

# Enable Waveshare DSI LCD display
dtoverlay=vc4-kms-v3d
dtoverlay=vc4-kms-dsi-waveshare-panel,4_0_inchC,rotation=90

# SPI and Overlay for Waveshare CAN Hat
dtparam=spi=on
dtoverlay=mcp2515-can0,oscillator=12000000,interrupt=25,spimaxfrequency=2000000
EOF


# -----------------------------------------------------------------------------
# Update Wayland / labwc for screen rotation
CFG="$USER_HOME/.config/labwc/autostart"

echo "Creating: $CFG"

mkdir -p "$(dirname "$CFG")"

cat > "$CFG" <<EOF
wlr-randr --output DSI-1 --transform 270
EOF

# -----------------------------------------------------------------------------
# Install dependencies
echo "Installing system dependencies"
apt update
apt install -y python3-dev python3-venv libgl1-mesa-dev libx11-dev glslang-tools

# -----------------------------------------------------------------------------
# Create virtual environment if it does not exist
if [ -d ".venv" ]; then
    echo "Virtual environment already exists. Skipping creation."
else
    echo "Creating virtual environment"
    python3 -m venv .venv
fi

. .venv/bin/activate

# -----------------------------------------------------------------------------
# Add environment variables
ENV_FILE=".env"
echo "Adding environment variables to $ENV_FILE"
rm -f "$ENV_FILE"
echo "EYE_ID=$EYE_ID" >> "$ENV_FILE"

# Add ENV vars to allow SSH user to start GUI application.
echo "Adding environment variables in $USER_BASHRC"
grep -qxF 'export DISPLAY=:0' "$USER_BASHRC" \
    || echo 'export DISPLAY=:0' >> "$USER_BASHRC"
grep -qxF "export XAUTHORITY=$USER_HOME/.Xauthority" "$USER_BASHRC" \
    || echo "export XAUTHORITY=$USER_HOME/.Xauthority" >> "$USER_BASHRC"

# -----------------------------------------------------------------------------
# Install requirements
echo "Installing Python dependencies from requirements.txt"
if [ -f "requirements.txt" ]; then
    pip install --upgrade pip
    pip install -r requirements.txt
else
    echo "requirements.txt not found!"
    exit 1
fi

# -----------------------------------------------------------------------------
# Install desktop wallpaper.
WALLPAPER_PATH="$ROOT_DIR/media/desktop.jpg"
PCMANFM_CONF="$USER_HOME/.config/pcmanfm/default/desktop-items-DSI-1.conf"

echo "Setting desktop background to $WALLPAPER_PATH"

if [ ! -f "$WALLPAPER_PATH" ]; then
    echo "Wallpaper not found: $WALLPAPER_PATH"
    exit 1
fi

# Create the config directory and file if they don't exist
if [ ! -f "$PCMANFM_CONF" ]; then
    echo "Config not found, creating: $PCMANFM_CONF"
    mkdir -p "$(dirname "$PCMANFM_CONF")"
    cat > "$PCMANFM_CONF" << EOF
[*]
wallpaper_mode=fit
wallpaper_common=1
wallpaper=$WALLPAPER_PATH
EOF
    echo "Wallpaper config created."
else
    if grep -q '^wallpaper=' "$PCMANFM_CONF"; then
        sed -i "s|^wallpaper=.*|wallpaper=$WALLPAPER_PATH|" "$PCMANFM_CONF"
    else
        echo "wallpaper=$WALLPAPER_PATH" >> "$PCMANFM_CONF"
    fi
    echo "Wallpaper updated."
fi

# -----------------------------------------------------------------------------
# Hide taskbar
CONFIG_DIR="$USER_HOME/.config/wf-panel-pi"
CONFIG_FILE="$CONFIG_DIR/wf-panel-pi.ini"

echo "Setting taskbar to autohide for user $USER_NAME. (Only visible using physical mouse.)"

mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" <<EOF
[panel]
autohide=true
autohide_duration=500
height=1
EOF

# -----------------------------------------------------------------------------
# Configure ethernet with static IP
IP_LAST_OCTET=$((100 + EYE_ID))
ETH_IP="192.168.5.${IP_LAST_OCTET}/24"

echo "Setting Ethernet IP to $ETH_IP"

# Find Ethernet connection associated with eth0
ETH_CON="$(nmcli -t -f NAME,DEVICE con show | grep ':eth0$' | cut -d: -f1 || true)"

# Fallback: first ethernet-type connection
if [ -z "$ETH_CON" ]; then
    ETH_CON="$(nmcli -t -f NAME,TYPE con show | grep -E ':ethernet$|:802-3-ethernet$' | cut -d: -f1 | head -n1 || true)"
fi

if [ -z "$ETH_CON" ]; then
    echo "No Ethernet connection profile found"
    exit 1
fi

echo "Using connection profile: $ETH_CON"

echo "Applying static configuration..."
nmcli con mod "$ETH_CON" \
    ipv4.method manual \
    ipv4.addresses "$ETH_IP" \
    ipv4.gateway "" \
    ipv4.dns "" \
    ipv4.never-default yes \
    ipv4.route-metric 900

echo "Bringing connection up..."
nmcli con up "$ETH_CON"

echo "Ethernet setup complete"

# -----------------------------------------------------------------------------
# Install main.service
echo "Installing service for main.sh"

tee /etc/systemd/system/main.service > /dev/null << EOF
[Unit]
Description=Main Service
After=multi-user.target

[Service]
Type=simple
WorkingDirectory=$USER_HOME/aEyes/eye
ExecStart=$USER_HOME/aEyes/eye/main.sh --service
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable main.service
systemctl restart main.service

echo "Run this command to see the service status: sudo systemctl status main.service"
echo "Run this command to see live logs: sudo journalctl -u main.service -f"

# -----------------------------------------------------------------------------
# Complete
echo ""
echo "Install complete."
echo "A reboot is required for updates to take effect!"
