#!/usr/bin/env bash
set -euo pipefail

# -----------------------------------------------------------------------------
# Check if the device is a Raspberry Pi
if grep -q "Raspberry Pi" /proc/device-tree/model; then
    echo "Installing service on a Raspberry Pi..."
else
    echo "This installation script is only for the Raspberry Pi!"
    exit 1
fi

# -----------------------------------------------------------------------------
# Must be run as root
if [ "$(id -u)" -ne 0 ]; then
    echo "This script must be run with sudo or as root"
    exit 1
fi

USER_NAME="${SUDO_USER:-$USER}"
USER_HOME=$(eval echo "~$USER_NAME")
USER_BASHRC="$USER_HOME/.bashrc"
ROOT_DIR="$(pwd -P)"

# -----------------------------------------------------------------------------
# Prompt for EYE_ID
printf "Enter EYE_ID (1 through 6): "
read EYE_ID

case "$EYE_ID" in
    ''|*[!0-9]*)
        echo "EYE_ID must be an integer"
        exit 1
        ;;
esac

if [ "$EYE_ID" -lt 1 ] || [ "$EYE_ID" -gt 6 ]; then
    echo "EYE_ID must be between 1 and 6"
    exit 1
fi

# -----------------------------------------------------------------------------
# Update firmare config.
CFG="/boot/firmware/config.txt"

sudo tee "$CFG" >/dev/null <<'EOF'
# Generated by install.sh
# Raspberry Pi firmware configuration

# Parameters from default installation
dtparam=audio=off
camera_auto_detect=0
auto_initramfs=1
arm_64bit=1
disable_overscan=1

[cm4]
otg_mode=1

[all]
# Reduce clocks for lower power consumption
arm_freq=600
gpu_freq=500
over_voltage=0

# Enable Waveshare DSI LCD display
dtoverlay=vc4-kms-v3d
dtoverlay=vc4-kms-dsi-waveshare-panel,4_0_inchC

# Enable primary UART on GPIO14/15
enable_uart=1

# Free PL011 UART0 from Bluetooth so it appears on GPIO14/15
dtoverlay=disable-bt
EOF

echo "Firmware config updates: $CFG"

# -----------------------------------------------------------------------------
# Create virtual environment if it does not exist
if [ ! -d ".venv" ]; then
    python3 -m venv .venv
fi

. .venv/bin/activate

# Add environmental variables
ENV_FILE=".env"
rm -f "$ENV_FILE"
echo "EYE_ID=$EYE_ID" >> "$ENV_FILE"
echo "EYE_ID=$EYE_ID stored in .env"

# -----------------------------------------------------------------------------
# Add environment variables to the user's .bashrc allow to use the display over SSH.
# Add DISPLAY only if missing
grep -qxF 'export DISPLAY=:0' "$USER_BASHRC" \
    || echo 'export DISPLAY=:0' >> "$USER_BASHRC"

# Add XAUTHORITY only if missing
grep -qxF "export XAUTHORITY=$USER_HOME/.Xauthority" "$USER_BASHRC" \
    || echo "export XAUTHORITY=$USER_HOME/.Xauthority" >> "$USER_BASHRC"

echo "Environment variables added in $USER_BASHRC"


# Install requirements
if [ -f "requirements.txt" ]; then
    pip install --upgrade pip
    pip install -r requirements.txt
else
    echo "requirements.txt not found"
    exit 1
fi
echo "Dependancies installed."

# -----------------------------------------------------------------------------
# Install desktop wallpaper.
WALLPAPER_PATH="$ROOT_DIR/media/desktop.jpg"
PCMANFM_CONF="$USER_HOME/.config/pcmanfm/default/desktop-items-DSI-1.conf"

if [ ! -f "$WALLPAPER_PATH" ]; then
    echo "Wallpaper not found: $WALLPAPER_PATH"
    exit 1
fi

if [ ! -f "$PCMANFM_CONF" ]; then
    echo "Error: $PCMANFM_CONF does not exist. Cannot update wallpaper."
    exit 1
fi

if grep -q '^wallpaper=' "$PCMANFM_CONF"; then
    sed -i "s|^wallpaper=.*|wallpaper=$WALLPAPER_PATH|" "$PCMANFM_CONF"
else
    echo "wallpaper=$WALLPAPER_PATH" >> "$PCMANFM_CONF"
fi

echo "Desktop background set to $WALLPAPER_PATH"

# -----------------------------------------------------------------------------
# Hide taskbar
CONFIG_DIR="$USER_HOME/.config/wf-panel-pi"
CONFIG_FILE="$CONFIG_DIR/wf-panel-pi.ini"

mkdir -p "$CONFIG_DIR"

cat > "$CONFIG_FILE" <<EOF
[panel]
autohide=true
autohide_duration=500
height=1
EOF

echo "Taskbar set to autohide for user $USER_NAME. Only visible using physical mouse."

# -----------------------------------------------------------------------------
# Configure ethernet with static IP:
IP_LAST_OCTET=$((200 + EYE_ID))
ETH_IP="192.168.1.${IP_LAST_OCTET}/24"

# Find Ethernet connection associated with eth0 (active or not)
ETH_CON="$(nmcli -t -f NAME,DEVICE con show | grep ':eth0$' | cut -d: -f1)"

# Fallback: first ethernet-type connection
if [ -z "$ETH_CON" ]; then
    ETH_CON="$(nmcli -t -f NAME,TYPE con show | grep -E ':ethernet$|:802-3-ethernet$' | cut -d: -f1 | head -n1)"
fi

if [ -z "$ETH_CON" ]; then
    echo "No Ethernet connection profile found"
    exit 1
fi

# Configure static IP on ethernet
# Set the route-metric to prefer wifi
nmcli con mod "$ETH_CON" \
    ipv4.method manual \
    ipv4.addresses "$ETH_IP" \
    ipv4.gateway "" \
    ipv4.dns "" \
    ipv4.never-default yes \
    ipv4.route-metric 900

nmcli con up "$ETH_CON"
echo "Ethernet IP set to $ETH_IP"

# -----------------------------------------------------------------------------
# Install main.service 
sudo tee /etc/systemd/system/main.service > /dev/null << EOF
[Unit]
Description=Main Service
After=multi-user.target         

[Service]
Type=simple
WorkingDirectory=$HOME/aEyes/src
ExecStart=$HOME/aEyes/eyes/main.sh --service
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable main.service
sudo systemctl stop main.service
sudo systemctl start main.service

echo "Service installation complete"
echo "Run this command to see the service status: sudo systemctl status main.service"
echo "Run this command to see live logs: sudo journalctl -u main.service -f"

# -----------------------------------------------------------------------------
# Complete
echo "Setup complete."
echo "A reboot is required for updates to take effect!"
